name = "stm32_drivers"
description = "Drivers for the stm32 dev boards"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/ohenley/stm32_drivers"

authors = ["AdaCore"]
maintainers = ["olivier henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

#[configuration.values.stm32_config]
#mcu = "stm32f746x"
#runtime = "embedded"

[[depends-on]]
gnat_arm_elf = "^12"
stm32_config = "1.0.0"
beta_types = "1.0.0"
hal_embedded = "1.0.0"
arm_cortex = "1.0.0"
stm32_svd = "1.0.0"
stm32_middleware = "1.0.0"


#stm32_adc_driver = {type = "Boolean", default = false}
#dac = {type = "Boolean", default = false}
#dcmi = {type = "Boolean", default = false}
#device_id = {type = "Boolean", default = false}
#dma = {type = "Boolean", default = false}
#dma2d = {type = "Boolean", default = false}
#dsi = {type = "Boolean", default = false}
#exti = {type = "Boolean", default = false}
#fmc = {type = "Boolean", default = false}
#gpio = {type = "Boolean", default = true}
#i2c = {type = "Boolean", default = false}
#i2s = {type = "Boolean", default = false}
#iwdg = {type = "Boolean", default = false}
#ltdc = {type = "Boolean", default = false}
#power_control = {type = "Boolean", default = false}
#pwm = {type = "Boolean", default = false}
#rng = {type = "Boolean", default = false}
#rtc = {type = "Boolean", default = false}
#sai = {type = "Boolean", default = false}
#sd = {type = "Boolean", default = false}
#spi = {type = "Boolean", default = false}
#syscfg = {type = "Boolean", default = false}
#timers = {type = "Boolean", default = false}
#uart = {type = "Boolean", default = false}


